add a bruteforce #bubble-sort
Teshager21/ruby-bubble-sort pull request #1
Opened 2020-05-25 17:37 UTC by Teshager21

2020-05-25 23:41 UTC, Torres-ssf approved these changes

2020-05-25 23:43 UTC, Torres-ssf requested changes
### Changes required :muscle: 
Hi there team :hand: 
Congratulations. your bubble sort was properly implemented. :clap: :clap: :clap: 
However there are some changes to be made before moving on.

- [ ] It's best practice to summarize all changes made in the PR description. You can learn more about that [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/). The print of the requirement can be found [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png).

- [ ] I notice that there is a broken link on your README file. It's best practice to leave the README file as clean as possible.

Please kindly submit for code review again after making these changes.
Feel free to message me on Slack if you have any questions about it.

Happy coding :computer: 
**Sergio Torres**

2020-05-26 05:27 UTC, Teshager21 commented
Implemented all the changes requested by the TSE.

2020-05-26 09:23 UTC, nikasulo approved these changes
# Great work! @Teshager21 and @chirchir12 :medal_military: 
Please merge and keep moving forward, I wish you the very best and see you at the top :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-05-26 10:24 UTC, merged